server:
  port: 9094
#虚拟ip
tttare:
  server-ip: 172.17.6.85
  version: v1.1

spring:
  application:
    name: kuuga-user-center
  #通用数据源配置 pg数据库
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://172.17.6.84:5432/test?searchpath=project101
#    username: postgres
#    password: pgcet123Cet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.6.134:5433/test?searchpath=project101
    username: postgres
    password: LPwarrior123456

#--------------------mybatis plus --------------
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

#--------------------eureka---------------------
eureka:
  client:
    service-url:
      defaultZone: http://${tttare.server-ip}:1001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}:${tttare.version} #修改Eureka上的默认描述信息
    metadata-map:
      version: ${tttare.version}

#---------------------OAuth2---------------------
#security:
#  oauth2:
#    client:
#      access-token-uri: http://${tttare.server-ip}:${server.port}/auth/oauth/token
#      user-authorization-uri: http://${tttare.server-ip}:${server.port}/auth/oauth/authorize
#      client-id: web
#    resource:
#      user-info-uri:  http://${tttare.server-ip}:${server.port}/auth/kuuga/member
#      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
