server:
  port: 8099
#虚拟ip
tttare:
  server-ip: 172.17.6.85

spring:
  application:
    name: kuuga-server-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/tttare/config-center
#          username: tttare
#          password: Qyk2438382779
#          basedir: D:/cloud-config
#          force-pull: true
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
  #------------------Rabbit MQ------------------------
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#--------------------eureka---------------------
eureka:
  client:
    service-url:
      defaultZone: http://${tttare.server-ip}:1001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} #修改Eureka上的默认描述信息

#--------------------spring cloud bus------------
#暴露/bus-refresh接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS