server:
  port: 8091
#虚拟ip
tttare:
  server-ip: 172.17.6.85

spring:
  application:
    name: kuuga-zuul
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#--------------------eureka---------------------
eureka:
  client:
    service-url:
      defaultZone: http://${tttare.server-ip}:1001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} #修改Eureka上的默认描述信息

#--------------------Zuul 转发配置-----------------------
zuul:
  routes:
    resource:
      path: /resource/**
      serviceId: kuuga-resource-service
      sensitiveHeaders: "*"
    auth:
      path: /auth/**
      serviceId: kuuga-oauth2
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: kuuga-system-service
      sensitiveHeaders: "*"
    user-center:
      path: /user/**
      serviceId: kuuga-user-center
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  add-proxy-headers: true

#---------------------OAuth2---------------------
#security:
#  oauth2:
#    client:
#      access-token-uri: http://${tttare.server-ip}:${server.port}/auth/oauth/token
#      user-authorization-uri: http://${tttare.server-ip}:${server.port}/auth/oauth/authorize
#      client-id: web
#    resource:
#      user-info-uri:  http://${tttare.server-ip}:${server.port}/auth/kuuga/member
#      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#------------------灰度配置----------------------
#正式环境微服务版本
#gray:
#  #微服务稳定版本配置
#  stableConfig:
#    kuuga-USER-center: v1.0
#    kuuga-pay-service: v1.0
#    kuuga-point-service: v1.0
#  #项目灰度服务配置
#  grayProjectConfig: [{projectId: 101,linkServersVersion: {kuuga-user-CENTER: v1.0,kuuga-pay-service: v1.0}},{projectId: 102,linkServersVersion: {kuuga-user-center: v1.1,kuuga-pay-service: v1.1}}]